/**
 * OmniCoin Integration Configuration for Validator
 *
 * This file is AUTO-GENERATED by scripts/sync-contract-addresses.sh
 * DO NOT EDIT MANUALLY - Run the sync script instead
 *
 * Source: Coin/deployments/localhost.json
 */

/**
 * Contract addresses for OmniCoin ecosystem
 */
export interface ContractAddresses {
  /** RPC URL for the network */
  rpcUrl: string;
  /** Avalanche Subnet ID (for avalanchego track-subnets config) */
  subnetId: string;
  /** Avalanche Blockchain ID (for RPC URL construction) */
  blockchainId: string;
  /** Chain ID for EVM transactions */
  chainId: number;
  /** OmniCoin ERC20 token contract address */
  OmniCoin: string;
  /** OmniCore main contract address */
  OmniCore: string;
  /** OmniGovernance DAO contract address */
  OmniGovernance: string;
  /** OmniBridge cross-chain bridge contract address */
  OmniBridge: string;
  /** PrivateOmniCoin privacy token contract address */
  PrivateOmniCoin: string;
  /** PrivateDEX privacy DEX contract address (COTI only) */
  PrivateDEX?: string;
  /** MinimalEscrow marketplace escrow contract address */
  MinimalEscrow: string;
  /** LegacyBalanceClaim legacy migration contract address */
  LegacyBalanceClaim: string;
}

/**
 * Contract addresses mapped by network name
 * Auto-generated from Coin/deployments/*.json
 */
export const OMNICOIN_ADDRESSES: Record<string, ContractAddresses> = {
  // Local Hardhat network (chainId: 131313) - Points to current Fuji deployment
  // ⚠️  CRITICAL: These addresses MUST match Coin/deployments/localhost.json
  // Last deployed: 2025-11-10 (Fresh L1 deployment)
  // Synchronized by: scripts/sync-contract-addresses.sh
  hardhat: {
    rpcUrl: 'http://127.0.0.1:9650/ext/bc/2FYUT2FZenR4bUZUGjVaucXmQgqmDnKmrioLNdPEn7RqPwunMw/rpc',
    subnetId: '2QWHbdAG4Q53NBF5baKB3mzKycByQtXvFGDjPKTFHLyVco2PR8',
    blockchainId: '2FYUT2FZenR4bUZUGjVaucXmQgqmDnKmrioLNdPEn7RqPwunMw',
    chainId: 131313,
    OmniCoin: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
    OmniCore: '0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e',
    OmniGovernance: '0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0',
    OmniBridge: '0x0000000000000000000000000000000000000000',
    PrivateOmniCoin: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
    MinimalEscrow: '0x8A791620dd6260079BF849Dc5567aDC3F2FdC318',
    LegacyBalanceClaim: '0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE',
  },

  // Fuji Testnet Subnet-EVM (chainId: 131313)
  // ⚠️  CRITICAL: These addresses MUST match Coin/deployments/fuji.json
  // Last deployed: 2025-11-10 (Fresh L1 deployment)
  // Fresh L1 deployment with P-Chain registration (multi-validator support)
  fuji: {
    rpcUrl: 'http://127.0.0.1:9650/ext/bc/2FYUT2FZenR4bUZUGjVaucXmQgqmDnKmrioLNdPEn7RqPwunMw/rpc',
    subnetId: '2QWHbdAG4Q53NBF5baKB3mzKycByQtXvFGDjPKTFHLyVco2PR8',
    blockchainId: '2FYUT2FZenR4bUZUGjVaucXmQgqmDnKmrioLNdPEn7RqPwunMw',
    chainId: 131313,
    OmniCoin: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
    OmniCore: '0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e',
    OmniGovernance: '0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0',
    OmniBridge: '0x0000000000000000000000000000000000000000',
    PrivateOmniCoin: '0x5FC8d32690cc91D4c39d9d3abcBD16989F875707',
    MinimalEscrow: '0x8A791620dd6260079BF849Dc5567aDC3F2FdC318',
    LegacyBalanceClaim: '0x9A9f2CCfdE556A7E9Ff0848998Aa4a0CFD8863AE',
  },

  // Avalanche Mainnet Subnet-EVM (Production)
  // ⚠️  PLACEHOLDER: Update when deploying to mainnet
  // Will be synchronized from Coin/deployments/mainnet.json
  mainnet: {
    rpcUrl: 'https://mainnet-rpc.omnibazaar.com', // To be updated with actual RPC
    subnetId: '0000000000000000000000000000000000000000000000000000000000000000', // To be deployed
    blockchainId: '0000000000000000000000000000000000000000000000000000000000000000', // To be deployed
    chainId: 999999, // To be determined
    OmniCoin: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniCore: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniGovernance: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniBridge: '0x0000000000000000000000000000000000000000', // To be deployed
    PrivateOmniCoin: '0x0000000000000000000000000000000000000000', // To be deployed
    MinimalEscrow: '0x0000000000000000000000000000000000000000', // To be deployed
    LegacyBalanceClaim: '0x0000000000000000000000000000000000000000', // To be deployed
  },

  // COTI Testnet (Privacy Layer Development)
  // ⚠️  Will be updated by sync script after deployment
  // Will be synchronized from Coin/deployments/coti-testnet.json
  'coti-testnet': {
    rpcUrl: 'https://testnet.coti.io/rpc',
    subnetId: '0000000000000000000000000000000000000000000000000000000000000000',
    blockchainId: '0000000000000000000000000000000000000000000000000000000000000000',
    chainId: 7082400, // COTI Testnet chain ID (verified)
    OmniCoin: '0x0000000000000000000000000000000000000000', // Not deployed on COTI
    OmniCore: '0x0000000000000000000000000000000000000000', // Not deployed on COTI
    OmniGovernance: '0x0000000000000000000000000000000000000000', // Not deployed on COTI
    OmniBridge: '0x123522e908b34799Cf14aDdF7B2A47Df404c4d47', // OmniPrivacyBridgeSimple ✅ DEPLOYED 2025-11-13
    PrivateOmniCoin: '0x6BF2b6df85CfeE5debF0684c4B656A3b86a31675', // PrivateOmniCoinSimple ✅ DEPLOYED 2025-11-13
    PrivateDEX: '0xA242e4555CECF29F888b0189f216241587b9945E', // PrivateDEXSimple ✅ DEPLOYED 2025-11-13
    MinimalEscrow: '0x0000000000000000000000000000000000000000', // Not deployed on COTI
    LegacyBalanceClaim: '0x0000000000000000000000000000000000000000', // Not deployed on COTI
  },

  // COTI Mainnet (Privacy Layer - Future Integration)
  // ⚠️  PLACEHOLDER: Update when COTI integration is ready
  // Will be synchronized from Coin/deployments/coti-mainnet.json
  'coti-mainnet': {
    rpcUrl: 'https://mainnet.coti.io', // COTI mainnet RPC
    subnetId: '0000000000000000000000000000000000000000000000000000000000000000', // Not applicable
    blockchainId: '0000000000000000000000000000000000000000000000000000000000000000', // Native COTI chain
    chainId: 1353, // COTI mainnet chain ID
    OmniCoin: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniCore: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniGovernance: '0x0000000000000000000000000000000000000000', // To be deployed
    OmniBridge: '0x0000000000000000000000000000000000000000', // Cross-chain bridge
    PrivateOmniCoin: '0x0000000000000000000000000000000000000000', // Privacy token (primary)
    MinimalEscrow: '0x0000000000000000000000000000000000000000', // To be deployed
    LegacyBalanceClaim: '0x0000000000000000000000000000000000000000', // Not applicable
  },
};

/**
 * Detect network based on environment variables or RPC URL
 * @returns Network name - ALWAYS returns 'fuji' (Hardhat/local development deprecated)
 */
export function detectNetwork(): string {
  // ARCHITECTURE DECISION (2025-11-03):
  // OmniCoin validators ONLY connect to Fuji Subnet-EVM testnet
  // Hardhat local development is DEPRECATED (was part of old TS consensus)
  //
  // With avalanchego handling consensus, we connect to deployed Fuji blockchain
  // just like a web3 app connects to Ethereum mainnet

  // Always return 'fuji' for current architecture
  return 'fuji';
}

/**
 * Get contract addresses for a specific network
 * @param network - Network name (optional, auto-detected if not provided)
 * @returns Contract addresses for the specified network
 * @throws Error if network is not found
 */
export function getContractAddresses(network?: string): ContractAddresses {
  const targetNetwork = network || detectNetwork();
  const addresses = OMNICOIN_ADDRESSES[targetNetwork];
  if (!addresses) {
    throw new Error(`No contract addresses found for network: ${targetNetwork}`);
  }
  return addresses;
}
